name: Check Jenkins Master Build Status

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "main"
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run workflow on'
        required: true
        default: 'main'
  repository_dispatch:
    types: [trigger_workflow]

jobs:
  check-jenkins-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.branch || github.ref }}

      - name: Check Jenkins Build Status
        env:
          JENKINS_URL: ${{ secrets.JENKINS_URL }}
          JENKINS_USER: ${{ secrets.JENKINS_USER }}
          JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}
        run: |
          echo "$JENKINS_URL/job/master-build/lastBuild/api/json"
          echo "$JENKINS_USER:$JENKINS_TOKEN"
  
  retrigger-pull-requests:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Get Open Pull Requests
        id: get-prs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/pulls?state=open&base=main" \
            > pull_requests.json

      - name: Retrigger Workflows for Open PRs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Loop through each open PR
          pr_numbers=$(jq '.[].number' pull_requests.json)
          for pr in $pr_numbers; do
            # Get the source branch of the PR (head.ref)
            source_branch=$(jq -r ".[] | select(.number == $pr) | .head.ref" pull_requests.json)

            # Dispatch the repository event to trigger the workflow
            curl -s -X POST -H "Authorization: token $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github+json" \
              "https://api.github.com/repos/${{ github.repository }}/dispatches" \
              -d "{\"event_type\": \"trigger_workflow\", \"client_payload\": {\"branch\": \"$source_branch\"}}"
          done