name: Check Jenkins Master Build Status

on:
  pull_request:
    branches:
      - "**"
  workflow_dispatch:
    branches:
      - "**"

jobs:
  check-jenkins-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.branch || github.ref }}

      - name: Check Jenkins Build Status
        env:
          JENKINS_URL: ${{ secrets.JENKINS_URL }}
          JENKINS_USER: ${{ secrets.JENKINS_USER }}
          JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}
        run: |
          # Fetch the last master build and check if it's green or not
          # response=$(curl -s -u "$JENKINS_USER:$JENKINS_TOKEN" "$JENKINS_URL/job/master-build/lastBuild/api/json")
          # build_result=$(echo "$response" | jq -r '.result')
          
          # if [ "$build_result" != "SUCCESS" ]; then
          #  echo "Jenkins master build is not green. Current status: $build_result"
          #  exit 1
          # fi
          exit 1