name: Check Jenkins Master Build Status

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "main"
  workflow_dispatch:  # Manual trigger via GitHub UI or API
    inputs:
      branch:
        description: 'Branch name to run the workflow on'
        required: true
        default: 'main'  # This is for manual triggers only

jobs:
  check-jenkins-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Jenkins Build Status
        env:
          JENKINS_URL: ${{ secrets.JENKINS_URL }}
          JENKINS_USER: ${{ secrets.JENKINS_USER }}
          JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}
        run: |
          # Get last build status for master branch job
          # build_status=$(curl -s -u "$JENKINS_USER:$JENKINS_TOKEN" \
          #  "$JENKINS_URL/job/master-build/lastBuild/api/json" | \
          #  jq -r '.result')
          
          # Fail the workflow if build is not successful
          # if [[ "$build_status" != "SUCCESS" ]]; then
          #  echo "Last Jenkins build of master failed with status: $build_status"
          #  exit 1
          #fi

          echo "$JENKINS_URL/job/master-build/lastBuild/api/json"
          echo "$JENKINS_USER:$JENKINS_TOKEN"
  
  retrigger-pull-requests:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Get Open Pull Requests
        id: get-prs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/pulls?state=open&base=main" \
            > pull_requests.json

      - name: Retrigger Workflows for Open PRs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Loop through each open PR
          pr_numbers=$(jq '.[].number' pull_requests.json)
          for pr in $pr_numbers; do
            # Get the source branch of the PR (head.ref)
            source_branch=$(jq -r ".[] | select(.number == $pr) | .head.ref" pull_requests.json)

            # Dispatch the workflow to the source branch of the PR (just the branch name)
            curl -s -X POST -H "Authorization: token $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github+json" \
              "https://api.github.com/repos/${{ github.repository }}/actions/workflows/check-jenkins-master-build.yml/dispatches" \
              -d "{\"ref\": \"$source_branch\"}"
          done


