name: check-jenkins-master-build

on:
  pull_request:
    branches:
      - "**"
  workflow_dispatch:
    branches:
      - "**"

jobs:
  check-jenkins-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.branch || github.ref }}

      - name: Check Jenkins Build Status
        env:
          JENKINS_URL: ${{ secrets.JENKINS_URL }}
          JENKINS_USER: ${{ secrets.JENKINS_USER }}
          JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}
        run: |
          echo "First 3 characters of JENKINS_USER: ${JENKINS_USER:0:3}"
          echo "First 3 characters of JENKINS_TOKEN: ${JENKINS_TOKEN:0:3}"
          echo "URL: ${JENKINS_URL:0:25} (TEST)"

          crumb=$(curl -s -u "$JENKINS_USER:$JENKINS_TOKEN" "$JENKINS_URL/crumbIssuer/api/json" | jq -r '.crumb')
          response=$(curl -s -u "$JENKINS_USER:$JENKINS_TOKEN" -H "Jenkins-Crumb:$crumb" "$JENKINS_URL/job/shotgun/job/shotgun-app/job/master/lastBuild/api/json")

          echo "Response: $response"
          build_result=$(echo "$response" | jq -r '.result')

          if [ "$build_result" != "SUCCESS" ]; then
            echo "Jenkins master build is not green. Current status: $build_result"
            exit 1
          fi