name: retrigger-builds-on-merges

on:
  push:
    branches:
      - "**"

jobs:
  retrigger-pull-requests:
    # if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Run inline JavaScript
        uses: actions/github-script@v6
        with:
          script: |
            const GITHUB_TOKEN = process.env.GITHUB_TOKEN;
            const repository = process.env.GITHUB_REPOSITORY;

            // API URLs
            const pullsUrl = `https://api.github.com/repos/${repository}/pulls?state=open&base=main`;

            // Fetch open PRs targeting the main branch
            async () => {
              const pr_response = await fetch(pullsUrl, {
                headers: {
                  Authorization: `Bearer ${GITHUB_TOKEN}`,
                  Accept: 'application/vnd.github+json',
                },
              });

              if (!pr_response.ok) {
                throw new Error(`Failed to fetch PRs: ${pr_response.status} ${pr_response.statusText}`);
              }

              pr_response_data = response.json();

              console.log(pr_response_data);
              console.log(pullsUrl);
            };
