name: Retrigger Build Check On PRs

on:
  push:
    branches:
      - "main"

jobs:
  retrigger-pull-requests:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Retrigger Workflows for Open PRs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get open PRs
          prs=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/pulls?state=open&base=main")
          
          # For each PR, create a new check run
          echo "$prs" | jq -r '.[] | .head.sha + ";" + .number' | while IFS=";" read -r head_sha pr_number; do
            echo "Creating check run for PR $pr_number with SHA $head_sha"
            curl -L -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: token $GITHUB_TOKEN" \
              "https://api.github.com/repos/${{ github.repository }}/check-runs" \
              -d "{
                \"name\": \"Check Jenkins Master Build\",
                \"head_sha\": \"$head_sha\",
                \"status\": \"in_progress\",
                \"details_url\": \"https://github.com/${{ github.repository }}/pull/$pr_number\",
                \"external_id\": \"pr-$pr_number\",
                \"started_at\": \"$(date -u +"%Y-%m-%dT%H:%M:%SZ")\",
                \"output\": {
                  \"title\": \"Jenkins Master Build Check\",
                  \"summary\": \"Running Jenkins master build status check\"
                }
              }"
          done